################################################################################
# This file was auto-generated by generate_state_variable_form.py
################################################################################
import numpy as np


def calculate_eom(x, u, m, k, b):
    [z, zdot] = x.flatten()  # ensure 1D
    [F] = u.flatten()  # ensure 1D
    eom = np.array([[zdot], [0.2*F - 0.6*z - 0.1*zdot]])
    return eom.squeeze()
