################################################################################
# This file was auto-generated by generate_state_variable_form.py
################################################################################
import numpy as np


def calculate_eom(x, u, m_c, J_c, m_l, m_r, d, mu, g):
    [z, h, theta, zdot, hdot, thetadot] = x.flatten()  # ensure 1D
    [u_F, u_tau] = u.flatten()  # ensure 1D
    eom = np.array([[zdot], [hdot], [thetadot], [-1.46910863480421e-19*thetadot**2*np.cos(theta) - 0.666666666666667*u_F*np.sin(theta) - 0.0666666666666667*zdot], [-1.46910863480421e-19*thetadot**2*np.sin(theta) + 0.666666666666667*u_F*np.cos(theta) - 9.81], [20.3252032520325*u_tau]])
    return eom.squeeze()
