################################################################################
# This file was auto-generated by generate_state_variable_form.py
################################################################################
import numpy as np


def calculate_eom(x, u, m1, m2, ell, g):
    [z, Dummy_61, _Dummy_60, _Dummy_59] = x.flatten()  # ensure 1D
    [F] = u.flatten()  # ensure 1D
    eom = np.array([[Dummy_61], [_Dummy_59**2*z + 2.85714285714286*Dummy_61 - 9.8*np.sin(_Dummy_60)], [_Dummy_59], [-4.2*_Dummy_59*Dummy_61*z/(2.1*z**2 + 1.0) + 3.0*F*np.cos(_Dummy_60)/(2.1*z**2 + 1.0) - 20.58*z*np.cos(_Dummy_60)/(2.1*z**2 + 1.0) - 29.4*np.cos(_Dummy_60)/(2.1*z**2 + 1.0)]])
    return eom.squeeze()
